# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CalculatorDesign.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(483, 665)
        font = QtGui.QFont()
        font.setFamily("Avenir")
        font.setPointSize(35)
        Form.setFont(font)
        Form.setStyleSheet("background-color: rgb(169, 177, 235)\n"
"\n"
"")
        self.seven = QtWidgets.QPushButton(Form, clicked = lambda: self.press_it("7"))
        self.seven.setGeometry(QtCore.QRect(30, 160, 91, 81))
        font = QtGui.QFont()
        font.setFamily("Futura")
        font.setPointSize(36)
        font.setItalic(False)
        self.seven.setFont(font)
        self.seven.setAutoFillBackground(False)
        self.seven.setStyleSheet("background-color: rgb(45, 109, 167);\n"
"color: rgb(255, 255, 111);")
        self.seven.setCheckable(False)
        self.seven.setObjectName("seven")
        self.output = QtWidgets.QLabel(Form)
        self.output.setGeometry(QtCore.QRect(30, 30, 421, 101))
        font = QtGui.QFont()
        font.setFamily("Futura")
        font.setPointSize(36)
        font.setItalic(False)
        self.output.setFont(font)
        self.output.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.output.setAutoFillBackground(False)
        self.output.setStyleSheet("background-color: rgb(255, 255, 138);\n"
"color: rgb(135, 0, 6);")
        self.output.setFrameShape(QtWidgets.QFrame.Box)
        self.output.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.output.setLineWidth(2)
        self.output.setMidLineWidth(0)
        self.output.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.output.setIndent(-2)
        self.output.setObjectName("output")
        self.eight = QtWidgets.QPushButton(Form, clicked = lambda: self.press_it("8"))
        self.eight.setGeometry(QtCore.QRect(140, 160, 91, 81))
        font = QtGui.QFont()
        font.setFamily("Futura")
        font.setPointSize(36)
        font.setItalic(False)
        self.eight.setFont(font)
        self.eight.setAutoFillBackground(False)
        self.eight.setStyleSheet("background-color: rgb(45, 109, 167);\n"
"color: rgb(255, 255, 111);")
        self.eight.setCheckable(False)
        self.eight.setObjectName("eight")
        self.nine = QtWidgets.QPushButton(Form, clicked = lambda: self.press_it("9"))
        self.nine.setGeometry(QtCore.QRect(250, 160, 91, 81))
        font = QtGui.QFont()
        font.setFamily("Futura")
        font.setPointSize(36)
        font.setItalic(False)
        self.nine.setFont(font)
        self.nine.setAutoFillBackground(False)
        self.nine.setStyleSheet("background-color: rgb(45, 109, 167);\n"
"color: rgb(255, 255, 111);")
        self.nine.setCheckable(False)
        self.nine.setObjectName("nine")
        self.dividesign = QtWidgets.QPushButton(Form, clicked = lambda: self.press_it("/"))
        self.dividesign.setGeometry(QtCore.QRect(360, 160, 91, 81))
        font = QtGui.QFont()
        font.setFamily("Futura")
        font.setPointSize(36)
        font.setItalic(False)
        self.dividesign.setFont(font)
        self.dividesign.setAutoFillBackground(False)
        self.dividesign.setStyleSheet("background-color: rgb(255, 137, 50);\n"
"color: rgb(255, 224, 220)")
        self.dividesign.setCheckable(False)
        self.dividesign.setObjectName("dividesign")
        self.four = QtWidgets.QPushButton(Form, clicked = lambda: self.press_it("4"))
        self.four.setGeometry(QtCore.QRect(30, 260, 91, 81))
        font = QtGui.QFont()
        font.setFamily("Futura")
        font.setPointSize(36)
        font.setItalic(False)
        self.four.setFont(font)
        self.four.setAutoFillBackground(False)
        self.four.setStyleSheet("background-color: rgb(45, 109, 167);\n"
"color: rgb(255, 255, 111);")
        self.four.setCheckable(False)
        self.four.setObjectName("four")
        self.fivre = QtWidgets.QPushButton(Form, clicked = lambda: self.press_it("5"))
        self.fivre.setGeometry(QtCore.QRect(140, 260, 91, 81))
        font = QtGui.QFont()
        font.setFamily("Futura")
        font.setPointSize(36)
        font.setItalic(False)
        self.fivre.setFont(font)
        self.fivre.setAutoFillBackground(False)
        self.fivre.setStyleSheet("background-color: rgb(45, 109, 167);\n"
"color: rgb(255, 255, 111);")
        self.fivre.setCheckable(False)
        self.fivre.setObjectName("fivre")
        self.six = QtWidgets.QPushButton(Form, clicked = lambda: self.press_it("6"))
        self.six.setGeometry(QtCore.QRect(250, 260, 91, 81))
        font = QtGui.QFont()
        font.setFamily("Futura")
        font.setPointSize(36)
        font.setItalic(False)
        self.six.setFont(font)
        self.six.setAutoFillBackground(False)
        self.six.setStyleSheet("background-color: rgb(45, 109, 167);\n"
"color: rgb(255, 255, 111);")
        self.six.setCheckable(False)
        self.six.setObjectName("six")
        self.one = QtWidgets.QPushButton(Form, clicked = lambda: self.press_it("1"))
        self.one.setGeometry(QtCore.QRect(30, 360, 91, 81))
        font = QtGui.QFont()
        font.setFamily("Futura")
        font.setPointSize(36)
        font.setItalic(False)
        self.one.setFont(font)
        self.one.setAutoFillBackground(False)
        self.one.setStyleSheet("background-color: rgb(45, 109, 167);\n"
"color: rgb(255, 255, 111);")
        self.one.setCheckable(False)
        self.one.setObjectName("one")
        self.two = QtWidgets.QPushButton(Form, clicked = lambda: self.press_it("2"))
        self.two.setGeometry(QtCore.QRect(140, 360, 91, 81))
        font = QtGui.QFont()
        font.setFamily("Futura")
        font.setPointSize(36)
        font.setItalic(False)
        self.two.setFont(font)
        self.two.setAutoFillBackground(False)
        self.two.setStyleSheet("background-color: rgb(45, 109, 167);\n"
"color: rgb(255, 255, 111);")
        self.two.setCheckable(False)
        self.two.setObjectName("two")
        self.three = QtWidgets.QPushButton(Form, clicked = lambda: self.press_it("3"))
        self.three.setGeometry(QtCore.QRect(250, 360, 91, 81))
        font = QtGui.QFont()
        font.setFamily("Futura")
        font.setPointSize(36)
        font.setItalic(False)
        self.three.setFont(font)
        self.three.setAutoFillBackground(False)
        self.three.setStyleSheet("background-color: rgb(45, 109, 167);\n"
"color: rgb(255, 255, 111);")
        self.three.setCheckable(False)
        self.three.setObjectName("three")
        self.zero = QtWidgets.QPushButton(Form, clicked = lambda: self.press_it("0"))
        self.zero.setGeometry(QtCore.QRect(140, 460, 91, 81))
        font = QtGui.QFont()
        font.setFamily("Futura")
        font.setPointSize(36)
        font.setItalic(False)
        self.zero.setFont(font)
        self.zero.setAutoFillBackground(False)
        self.zero.setStyleSheet("background-color: rgb(45, 109, 167);\n"
"color: rgb(255, 255, 111);")
        self.zero.setCheckable(False)
        self.zero.setObjectName("zero")
        self.mutiplysign = QtWidgets.QPushButton(Form, clicked = lambda: self.press_it("*"))
        self.mutiplysign.setGeometry(QtCore.QRect(360, 260, 91, 81))
        font = QtGui.QFont()
        font.setFamily("Futura")
        font.setPointSize(36)
        font.setItalic(False)
        self.mutiplysign.setFont(font)
        self.mutiplysign.setAutoFillBackground(False)
        self.mutiplysign.setStyleSheet("background-color: rgb(255, 137, 50);\n"
"color: rgb(255, 224, 220)")
        self.mutiplysign.setCheckable(False)
        self.mutiplysign.setObjectName("mutiplysign")
        self.minussign = QtWidgets.QPushButton(Form, clicked = lambda: self.press_it("-"))
        self.minussign.setGeometry(QtCore.QRect(360, 360, 91, 81))
        font = QtGui.QFont()
        font.setFamily("Futura")
        font.setPointSize(36)
        font.setItalic(False)
        self.minussign.setFont(font)
        self.minussign.setAutoFillBackground(False)
        self.minussign.setStyleSheet("background-color: rgb(255, 137, 50);\n"
"color: rgb(255, 224, 220)")
        self.minussign.setCheckable(False)
        self.minussign.setObjectName("minussign")
        self.plussign = QtWidgets.QPushButton(Form, clicked = lambda: self.press_it("+"))
        self.plussign.setGeometry(QtCore.QRect(360, 460, 91, 81))
        font = QtGui.QFont()
        font.setFamily("Futura")
        font.setPointSize(36)
        font.setItalic(False)
        self.plussign.setFont(font)
        self.plussign.setAutoFillBackground(False)
        self.plussign.setStyleSheet("background-color: rgb(255, 137, 50);\n"
"color: rgb(255, 224, 220)")
        self.plussign.setCheckable(False)
        self.plussign.setObjectName("plussign")

        self.equalsign = QtWidgets.QPushButton(Form, clicked = lambda: self.basicmath_it())
        self.equalsign.setGeometry(QtCore.QRect(30, 460, 91, 81))
        font = QtGui.QFont()
        font.setFamily("Futura")
        font.setPointSize(36)
        font.setItalic(False)
        self.equalsign.setFont(font)
        self.equalsign.setAutoFillBackground(False)
        self.equalsign.setStyleSheet("background-color: rgb(255, 98, 192);\n"
"color: rgb(199, 255, 158)")
        self.equalsign.setCheckable(False)
        self.equalsign.setObjectName("equalsign")
        self.dot = QtWidgets.QPushButton(Form, clicked = lambda: self.press_it("."))
        self.dot.setGeometry(QtCore.QRect(250, 460, 91, 81))
        font = QtGui.QFont()
        font.setFamily("Futura")
        font.setPointSize(36)
        font.setItalic(False)
        self.dot.setFont(font)
        self.dot.setAutoFillBackground(False)
        self.dot.setStyleSheet("background-color: rgb(127, 218, 218);\n"
"color: rgb(55, 48, 173)")
        self.dot.setCheckable(False)
        self.dot.setObjectName("dot")
        self.CE = QtWidgets.QPushButton(Form, clicked = lambda: self.remove_it())
        self.CE.setGeometry(QtCore.QRect(30, 560, 201, 81))
        font = QtGui.QFont()
        font.setFamily("Futura")
        font.setPointSize(36)
        font.setItalic(False)
        self.CE.setFont(font)
        self.CE.setAutoFillBackground(False)
        self.CE.setStyleSheet("background-color: rgb(97, 193, 143);\n"
"color: rgb(255, 241, 157)")
        self.CE.setCheckable(False)
        self.CE.setObjectName("CE")
        self.C = QtWidgets.QPushButton(Form, clicked = lambda: self.press_it("C"))
        self.C.setGeometry(QtCore.QRect(250, 560, 201, 81))
        font = QtGui.QFont()
        font.setFamily("Futura")
        font.setPointSize(36)
        font.setItalic(False)
        self.C.setFont(font)
        self.C.setAutoFillBackground(False)
        self.C.setStyleSheet("background-color: rgb(97, 193, 143);\n"
"color: rgb(255, 241, 157)")
        self.C.setCheckable(False)
        self.C.setObjectName("C")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def press_it(self, buttonpressed):
        if buttonpressed == "C":
                self.output.setText("0")

        else:
                #to start the output without 0 when already prssed the number button
                if self.output.text() == "0":
                        self.output.setText("")
                #to concatenate the prssed number tgt
                self.output.setText(f'{self.output.text()} {buttonpressed}')

    #decimeal(dot)
    def dot_it(self):
        label = self.output.text()
        if "." not in label:
                self.output.setText(f'{label}.')
        #if dot(".") already present, check if its a last character
        else:
                if label[-1] != ".":
                        #not a number, must be + - / *
                        if not label[-1].isnumeric():
                                self.output.setText(f'{label}')

    #remove recent character
    def remove_it(self):
        #get character that on the label already
        label = self.output.text()
        #remove the recent string
        label = label[:-2]
        #output back to the label
        self.output.setText(label)


    #basic math( + - x /)
    def basicmath_it(self):
        #get character that on the label already
        label = self.output.text()
        try:
                answer = eval(label)
                #output the answer to the screen
                self.output.setText(str(answer))
        except:
                #output error to the screen
                self.output.setText("ERROR")


    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.seven.setText(_translate("Form", "7"))
        self.output.setText(_translate("Form", "0"))
        self.eight.setText(_translate("Form", "8"))
        self.nine.setText(_translate("Form", "9"))
        self.dividesign.setText(_translate("Form", "/"))
        self.four.setText(_translate("Form", "4"))
        self.fivre.setText(_translate("Form", "5"))
        self.six.setText(_translate("Form", "6"))
        self.one.setText(_translate("Form", "1"))
        self.two.setText(_translate("Form", "2"))
        self.three.setText(_translate("Form", "3"))
        self.zero.setText(_translate("Form", "0"))
        self.mutiplysign.setText(_translate("Form", "X"))
        self.minussign.setText(_translate("Form", "-"))
        self.plussign.setText(_translate("Form", "+"))
        self.equalsign.setText(_translate("Form", "="))
        self.dot.setText(_translate("Form", "."))
        self.CE.setText(_translate("Form", "CE"))
        self.C.setText(_translate("Form", "C"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
